[project]
name = 'Stacks-Skills'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.constants]
path = 'contracts/constants.clar'
clarity_version = 2
epoch = 2.5

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
