[project]
name = 'Stacks-Skills'
description = 'SkillFlow - Bitcoin-native freelancing platform'
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'
[contracts.constants]
path = 'contracts/constants.clar'
clarity_version = 2
epoch = 2.5

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc-moc]
path = 'contracts/sbtc-moc.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip010-trait]
path = 'contracts/sip010-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.skillflow-main]
path = 'contracts/skillflow-main.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
